import http from'node:http';import{readFile}from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';import{Store,id}from'./store.mjs';import{evaluate,validateCampaign,validatePackage}from'./engine.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),store=new Store(path.resolve(process.env.DATA_DIR||path.join(root,'data')));await store.init();const port=Number(process.env.PORT||3000),mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'};
async function body(r){let x='';for await(const c of r){x+=c;if(x.length>2e6)throw Object.assign(new Error('Request too large'),{status:413})}return x?JSON.parse(x):{}}function send(r,s,x,t='application/json; charset=utf-8'){r.writeHead(s,{'content-type':t,'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY'});r.end(t.startsWith('application/json')?JSON.stringify(x):x)}function audit(c,a,actor='user',detail={}){c.audit.push({id:id(),at:new Date().toISOString(),action:a,actor,detail})}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{status:'ok',service:'OTA Evidence Hub',time:new Date().toISOString()});if(req.method==='GET'&&u.pathname==='/api/campaigns')return send(res,200,(await store.list()).map(c=>({id:c.id,name:c.name,release:c.release,vehicleProgramme:c.vehicleProgramme,owner:c.owner,updatedAt:c.updatedAt,assessment:evaluate(c)})));
 if(req.method==='POST'&&u.pathname==='/api/campaigns'){const x=await body(req),errors=validateCampaign(x);if(errors.length)return send(res,400,{errors});const c=await store.create({name:x.name.trim(),release:x.release.trim(),owner:x.owner.trim(),vehicleProgramme:x.vehicleProgramme.trim(),description:x.description||'',safetyRelevant:Boolean(x.safetyRelevant),regulatedMarket:Boolean(x.regulatedMarket),personalData:Boolean(x.personalData),packages:[],cohorts:[],evidence:[],gates:[],reviews:[],audit:[]});audit(c,'CAMPAIGN_CREATED',c.owner);await store.save(c);return send(res,201,{...c,assessment:evaluate(c)})}
 const m=u.pathname.match(/^\/api\/campaigns\/([a-f0-9-]+)(?:\/(packages|cohorts|evidence|gates|reviews|report))?$/i);if(m&&req.method==='GET'&&!m[2]){const c=await store.get(m[1]);return send(res,200,{...c,assessment:evaluate(c)})}if(!m)return req.method==='GET'?staticFile(u,res):send(res,404,{error:'Not found'});const c=await store.get(m[1]);if(req.method==='GET'&&m[2]==='report')return send(res,200,{schemaVersion:'1.0',campaign:c,assessment:evaluate(c)});if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const x=await body(req);
 if(m[2]==='packages'){const e=validatePackage(x);if(e.length)return send(res,400,{errors:e});const p={id:id(),name:x.name.trim(),version:x.version.trim(),ecu:x.ecu.trim(),checksum:x.checksum.trim(),signed:Boolean(x.signed),signatureRef:x.signatureRef||'',dependencies:x.dependencies||[],rollbackVersion:x.rollbackVersion||'',sizeMb:Number(x.sizeMb||0)};c.packages.push(p);audit(c,'PACKAGE_ADDED',x.actor,{packageId:p.id})}
 if(m[2]==='cohorts'){if(!x.name?.trim()||!x.ring?.trim())return send(res,400,{error:'Cohort name and ring are required.'});const p={id:id(),name:x.name.trim(),ring:x.ring.trim(),vehicleCount:Number(x.vehicleCount||0),variants:x.variants||[],regions:x.regions||[],entryCriteria:x.entryCriteria||'',exitCriteria:x.exitCriteria||''};c.cohorts.push(p);audit(c,'COHORT_ADDED',x.actor,{cohortId:p.id})}
 if(m[2]==='evidence'){if(!x.title?.trim()||!x.type?.trim())return send(res,400,{error:'Evidence title and type are required.'});const e={id:id(),title:x.title.trim(),type:x.type.trim(),reference:x.reference||'',hash:x.hash||'',status:x.status||'UNREVIEWED',validUntil:x.validUntil||'',owner:x.owner||''};c.evidence.push(e);audit(c,'EVIDENCE_ADDED',x.actor,{evidenceId:e.id})}
 if(m[2]==='gates'){if(!x.name?.trim())return send(res,400,{error:'Gate name is required.'});const g={id:id(),name:x.name.trim(),status:x.status||'OPEN',owner:x.owner||'',criteria:x.criteria||'',notes:x.notes||''};c.gates.push(g);audit(c,'GATE_RECORDED',x.actor,{gateId:g.id,status:g.status})}
 if(m[2]==='reviews'){if(!x.reviewer?.trim()||!['APPROVED','REWORK','REJECTED'].includes(x.disposition))return send(res,400,{error:'Reviewer and valid disposition are required.'});const r={id:id(),reviewer:x.reviewer.trim(),role:x.role||'Release authority',disposition:x.disposition,notes:x.notes||'',at:new Date().toISOString()};c.reviews.push(r);audit(c,'REVIEW_RECORDED',r.reviewer,{reviewId:r.id,disposition:r.disposition})}
 await store.save(c);return send(res,200,{...c,assessment:evaluate(c)})}
async function staticFile(u,res){const f=u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''),t=path.join(root,'public',path.normalize(f));if(!t.startsWith(path.join(root,'public')))return send(res,403,{error:'Forbidden'});try{return send(res,200,await readFile(t),mime[path.extname(t)]||'application/octet-stream')}catch{return send(res,404,{error:'Not found'})}}
http.createServer((q,s)=>route(q,s).catch(e=>{console.error(e);send(s,e.status||500,{error:e.message||'Unexpected error'})})).listen(port,'0.0.0.0',()=>console.log(`OTA Evidence Hub listening on ${port}`));
